Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Modules\Authentification\Http\Controllers\AuthentificationController;
use Modules\Authentification\Http\Controllers\DashboardController;
use Modules\Authentification\Http\Controllers\MenuController;
use Modules\Authentification\Http\Controllers\MenuManagerController;
use Modules\Authentification\Http\Controllers\RoleController;
use Modules\Authentification\Http\Controllers\SearchController;
use Modules\Authentification\Http\Controllers\UserController;


// Auth Route
Route::get('login', [AuthentificationController::class, 'showLogin'])->name('login');
Route::post('login', [AuthentificationController::class, 'login'])->name('login.post');
Route::post('logout', [AuthentificationController::class, 'logout'])->name('logout');


Route::middleware('auth')->group(function () {
    // Search Route
    Route::get('search/roles', [SearchController::class, 'roles'])->name('auth.searchRole');
    Route::get('search/module', [SearchController::class, 'modules'])->name('auth.searchModule');

    // Dashboard Route
    Route::resource('home', DashboardController::class);

    //  Users Route
    Route::resource('users', UserController::class);

    // Roles Route
    Route::resource('roles', RoleController::class);

    // Menu Route
    Route::resource('module', MenuController::class);

    // Menu Manager Route
    Route::post('menu-manager/changeHierarchy', [MenuManagerController::class, 'changeHierarchy'])->name('menu-manager.changeHierarchy');
    Route::resource('menu-manager', MenuManagerController::class);
});

Http/Controllers/RoleController.php
<?php

namespace Modules\Authentification\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Nwidart\Modules\Facades\Module;
use DataTables;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Modules\Authentification\Traits\ResponseStatus;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Str;
use Modules\Authentification\Entities\Menu;

class RoleController extends Controller
{
    use ResponseStatus;
    public function __construct()
    {
        $this->middleware('permission:role-index', ['only' => ['index']]);
        $this->middleware('permission:role-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:role-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:role-delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index(Request $request)
    {
        $config = [
            'title' => 'Roles'
        ];
        $config['breadcrumbs'] = [
            ['label' => 'List Roles']
        ];
        if ($request->ajax()) {
            $data = Role::all();
            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function ($row) {
                    $actionBtn = '<div class="btn-group dropend">
                           <button type="button" class="btn btn-outline-info dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                               Aksi
                           </button>
                           <ul class="dropdown-menu">
                               <li><a class="dropdown-item" href="' . route('roles.edit', $row->id) . '">Edit</a></li>
                               <li><a class="dropdown-item btn-delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" data-id ="' . $row->id . '" >Hapus</a></li>
                           </ul>
                         </div>';
                    return $actionBtn;
                })->make(true);
        }

        // dd(module_path('Authentification'));
        return view('authentification::layouts.role.index', compact('config'));
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        $config = [
            'title' => 'Tambah Role'
        ];

        $config['form'] = (object)[
            'method' => 'POST',
            'action' => route('roles.store')
        ];
        $config['breadcrumbs'] = [
            ['label' => 'List Roles', 'href' => route('roles.index')],
            ['label' => 'Tambah Role']
        ];

        $module = Menu::with('permissions')->get();

        return view('authentification::layouts.role.form', compact('config', 'module'));
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name'          => 'required|unique:roles',
        ]);

        if ($validator->passes()) {
            DB::beginTransaction();
            try {

                $role = new Role;
                $role->guard_name   = 'web';
                $role->name         = $request['name'];
                $role->slug         = Str::slug($request['name']);
                $role->save();


                DB::commit();
                $response = Response()->json($this->responseStore(true, NULL, route('roles.index')));
            } catch (Throwable $throw) {
                dd($throw);
                DB::rollBack();
                $response = response()->json(['error' => $throw]);
            }
        } else {
            $response = response()->json(['error' => $validator->errors()->all()]);
        }
        return $response;
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        return view('authentification::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        $config['title'] = "Edit Role";

        $data = Role::find($id);


        $config['form'] = (object)[
            'method' => 'PUT',
            'action' => route('roles.update', $id)
        ];
        $config['breadcrumbs'] = [
            ['label' => 'List Roles', 'href' => route('roles.index')],
            ['label' => 'Edit Role']
        ];
        $module = Menu::with('permissions')->get();

        return view('authentification::layouts.role.form', compact('config', 'data', 'module'));
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|unique:roles,name,' . $request['name'] . ',name',
        ]);

        if ($validator->passes()) {
            DB::beginTransaction();
            try {
                $role = Role::findorfail($id);
                $role->guard_name   = 'web';
                $role->name         = $request['name'];
                $role->slug = Str::slug($request['name']);
                $role->save();

                $role->syncPermissions($request->permissions);

                DB::commit();
                $response = response()->json($this->responseStore(true, NULL, route('roles.index')));
            } catch (Throwable $throw) {
                dd($throw);
                DB::rollBack();
                $response = response()->json(['error' => $throw]);
            }
        } else {
            $response = response()->json(['error' => $validator->errors()->all()]);
        }
        return $response;
    }
    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy(Role $role)
    {

        $response = response()->json([
            'status' => 'error',
            'message' => 'Data gagal dihapus'
        ]);
        DB::beginTransaction();

        try {
            $role->delete();
            $response = response()->json([
                'status' => 'success',
                'message' => 'Data berhasil dihapus'
            ]);
            DB::commit();
        } catch (Throwable $throw) {
            dd($throw);
            $response = response()->json(['error' => $throw]);
        }

        return $response;
    }
}

Resources/views/layouts/role/form.blade.php
@extends('authentification::layouts.main')
@section('contents')
<form id="formStore" action="{{ $config['form']->action }}" method="POST">
  @method($config['form']->method)
  @csrf
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <div class="row">
            <div class="col-md-6 col-12 d-flex justify-content-center justify-content-md-start align-items-center mb-3 mb-md-0">
              <h3 class="card-title">Tambah Role</h3>
            </div>
            <div class="col-md-6 col-12 d-flex justify-content-center justify-content-md-end align-items-baseline mb-md-0 mb-2">
              <div class="btn-group float-md-right" role="group" aria-label="Button group with nested dropdown">
                <a onclick="history.back()" class="btn btn-outline-primary float-end">
                  <i class="fa-solid fa-rotate-left"></i> Kembali
                </a>
                <button type="submit" class="btn btn-success text-white float-end">
                  <i class="fa-solid fa-plus"></i> Simpan
                </button>
              </div>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div id="errorCreate" class="mb-3" style="display:none;">
            <div class="alert alert-danger" role="alert">
              <div class="alert-icon"><i class="flaticon-danger text-danger"></i></div>
              <div class="alert-text">
              </div>
            </div>
          </div>
          <label class="form-label" for="name">Nama :</label>
          <input type="text" class="form-control" value="{{ $data->name ?? '' }}" name="name" id="name">
        </div>
      </div>
      <div class="card">
        <div class="card-header">
          <div class="row">
            <div class="col-md-6 col-12 d-flex justify-content-center justify-content-md-start align-items-center mb-3 mb-md-0">
              <h3 class="card-title">Module Permissions</h3>
            </div>
          </div>
        </div>
        <div class="accordion" id="accordionPanelsStayOpenExample">
          @foreach ($module as $item )
          <div class="accordion-item">
            <h2 class="accordion-header collapsed" id="heading-{{$item->id}}">
              <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-{{$item->id}}" aria-expanded="false" aria-controls="collapse-{{$item->id}}">
                {{$item->name}}
              </button>
            </h2>
            <div id="collapse-{{$item->id}}" class="accordion-collapse collapse" aria-labelledby="heading-{{$item->id}}">
              <div class="accordion-body">
                @php
                $col = 0 ;
                $role = \Spatie\Permission\Models\Role::find($data->id);
                @endphp
                @foreach ($item->permissions as $permission )
                @if ($col == 0)
                <div class="row">
                  @endif
                  <div class="col-md-3">
                    <div class="form-check form-check-inline">
                      <input class="form-check-input" type="checkbox" name="permissions[]" id="permission{{ $permission->id }}" value="{{ $permission->name }}" {{ isset($role) && $role->hasPermissionTo($permission->name) ? 'checked' : '' }}>
                      <label class="form-check-label" for="permission{{ $permission->id }}">{{ $permission->name }}</label>
                    </div>
                  </div>
                  @if ($col == 5)
                  @php
                  $col = 0;
                  @endphp
                </div>
                @else
                @php
                $col++;
                @endphp
                @endif
                @endforeach
              </div>
            </div>
          </div>
          @endforeach
        </div>
      </div>
    </div>
  </div>
</form>


@endsection

@section('css')
<link rel="stylesheet" href="{{Module::asset('authentification:vendor/datatables/datatables.min.css')}}">
@endsection

@section('scripts')
<script src="{{Module::asset('authentification:vendor/datatables/datatables.min.js')}}"></script>
<script>
  $(document).ready(function() {
    $('.collapse').collapse
    $("#formStore").submit(function(e) {
      e.preventDefault();
      let form = $(this);
      let btnSubmit = form.find("[type='submit']");
      let btnSubmitHtml = btnSubmit.html();
      let url = form.attr("action");
      let data = new FormData(this);
      $.ajax({
        cache: false,
        processData: false,
        contentType: false,
        type: "POST",
        url: url,
        data: data,
        beforeSend: function() {
          btnSubmit.addClass("disabled").html('<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Loading...').prop("disabled", "disabled");
        },
        success: function(response) {
          let errorCreate = $('#errorCreate');
          errorCreate.css('display', 'none');
          errorCreate.find('.alert-text').html('');
          btnSubmit.removeClass("disabled").html(btnSubmitHtml).removeAttr("disabled");
          if (response.status === "success") {
            toastr.success(response.message, 'Success !');
            setTimeout(function() {
              if (response.redirect === "" || response.redirect === "reload") {
                location.reload();
              } else {
                location.href = response.redirect;
              }
            }, 1000);
          } else {
            toastr.error((response.message ? response.message : "Please complete your form"), 'Failed !');
            if (response.error !== undefined) {
              errorCreate.removeAttr('style');
              $.each(response.error, function(key, value) {
                errorCreate.find('.alert-text').append('<span style="display: block">' + value + '</span>');
              });
            }
          }
        },
        error: function(response) {
          btnSubmit.removeClass("disabled").html(btnSubmitHtml).removeAttr("disabled");
          toastr.error(response.responseJSON.message, 'Failed !');
        }
      });
    });
  });
</script>
@endsection

Resources/views/layouts/role/index.blade.php
@extends('authentification::layouts.main')
@section('contents')
<div class="card">
  <div class="card-header">
    <div class="row">
      <div class="col-md-6 col-12 d-flex justify-content-center justify-content-md-start align-items-center mb-3 mb-md-0">
        <h3 class="card-title">Daftar Role</h3>
      </div>
      <div class="col-md-6 col-12 d-flex justify-content-center justify-content-md-end align-items-baseline mb-md-0 mb-2">
        <div class="btn-group float-md-right" role="group" aria-label="Button group with nested dropdown">
          <a class="btn btn-outline-primary" href=""><i class="fa fa-sync-alt fa-fw"></i></a>
          <a class="btn btn-outline-primary" href="{{ route('roles.create') }}"><i class="fa fa-plus fa-fw"></i> Tambah</a>
        </div>
      </div>
    </div>
  </div>
  <div class="table-responsive">
    <table id="dt" class="table table-bordered w-100">
      <thead>
        <tr>
          <th>Nama</th>
          <th class="text-center">Aksi</th>
        </tr>
      </thead>
      <tbody></tbody>
    </table>
  </div>
</div>

<div id="confirmDeleteModal" class="modal fade">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Delete Item Confirm</h4>
        <button type="button" class="btn btn-outline-danger close" data-bs-dismiss="modal"><span>&times;</span></button>
      </div>
      <div class="modal-body">
        <input type="hidden" name="id" />
        <div class="alert alert-warning">
          <strong>Peringatan !</strong> Anda yakin menghapus data ini ?
        </div>
      </div>
      <div class="modal-footer">
        <div class="btn-group">
          <button type="button" class="btn btn-danger btn-sm" data-bs-dismiss="modal">No <i class="fa fa-fw fa-ban"></i></button>
          <button type="button" id="btnDelete" class="btn btn-success btn-sm">Yes <i class="fa fa-fw fa-check"></i></button>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection

@section('css')
<link rel="stylesheet" href="{{Module::asset('authentification:vendor/datatables/datatables.min.css')}}">
@endsection

@section('scripts')
<script src="{{Module::asset('authentification:vendor/datatables/datatables.min.js')}}"></script>
<script>
  $(document).ready(function() {
    $('#dt').dataTable({
      serverSide: true,
      processing: true,
      ajax: {
        url: `{{ route('roles.index') }}`
      },
      columns: [{
          data: 'name',
          name: 'name'
        },
        {
          data: 'action',
          name: 'action',
          className: "text-center",
          orderable: false,
          searchable: false
        },
      ],
      rowCallback: function(row, data) {
        let api = this.api();
        $(row).find('.btn-delete').click(function() {
          var pk = $(this).data('id'),
            url = `{{ route("roles.index") }}/` + pk;
          console.log(pk);

          $('#confirmDeleteModal').modal('toggle');

          $('#btnDelete').click(function(e) {
            e.preventDefault();
            $.ajax({
              url: url,
              type: "DELETE",
              data: {
                _token: '{{ csrf_token() }}',
                _method: 'DELETE'
              },
              error: function(response) {
                toastr.error(response, 'Failed !');
              },
              success: function(response) {
                if (response.status === "success") {
                  toastr.success(response.message, 'Success !');
                  $('#confirmDeleteModal').modal('hide');;
                  $('.modal-backdrop').remove();
                  api.draw();
                } else {
                  toastr.error((response.message ? response.message : "Please complete your form"), 'Failed !');
                }
              }
            });
          });
        });
      }
    });

  });
</script>
@endsection