Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Modules\Authentification\Http\Controllers\AuthentificationController;
use Modules\Authentification\Http\Controllers\DashboardController;
use Modules\Authentification\Http\Controllers\MenuController;
use Modules\Authentification\Http\Controllers\MenuManagerController;
use Modules\Authentification\Http\Controllers\RoleController;
use Modules\Authentification\Http\Controllers\SearchController;
use Modules\Authentification\Http\Controllers\UserController;


// Auth Route
Route::get('login', [AuthentificationController::class, 'showLogin'])->name('login');
Route::post('login', [AuthentificationController::class, 'login'])->name('login.post');
Route::post('logout', [AuthentificationController::class, 'logout'])->name('logout');


Route::middleware('auth')->group(function () {
    // Search Route
    Route::get('search/roles', [SearchController::class, 'roles'])->name('auth.searchRole');
    Route::get('search/module', [SearchController::class, 'modules'])->name('auth.searchModule');

    // Dashboard Route
    Route::resource('home', DashboardController::class);

    //  Users Route
    Route::resource('users', UserController::class);

    // Roles Route
    Route::resource('roles', RoleController::class);

    // Menu Route
    Route::resource('module', MenuController::class);

    // Menu Manager Route
    Route::post('menu-manager/changeHierarchy', [MenuManagerController::class, 'changeHierarchy'])->name('menu-manager.changeHierarchy');
    Route::resource('menu-manager', MenuManagerController::class);
});

Entities/Menu.php
<?php

namespace Modules\Authentification\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Spatie\Permission\Models\Permission;

class Menu extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function permissions()
    {
        return $this->hasMany(Permission::class, 'menu_id');
    }

    protected static function newFactory()
    {
        return \Modules\Authentification\Database\factories\MenuFactory::new();
    }
}

Http/Controllers/MenuController.php
<?php

namespace Modules\Authentification\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Authentification\Entities\Menu;
use DataTables;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Modules\Authentification\Traits\ResponseStatus;
use Spatie\Permission\Models\Permission;

class MenuController extends Controller
{
    use ResponseStatus;
    public function __construct()
    {
        $this->middleware('permission:modules-index', ['only' => ['index']]);
        $this->middleware('permission:modules-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:modules-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:modules-delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index(Request $request)
    {
        $config = [
            'title' => 'Module'
        ];
        $config['breadcrumbs'] = [
            ['label' => 'List Modules']
        ];


        if ($request->ajax()) {
            $data = Menu::latest();
            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function ($row) {
                    $actionBtn = '<div class="btn-group dropend">
                       <button type="button" class="btn btn-outline-info dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                           Aksi
                       </button>
                       <ul class="dropdown-menu">
                           <li><a class="dropdown-item" href="' . route('module.edit', $row->id) . '">Edit</a></li>
                           <li><a class="dropdown-item btn-delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" data-id ="' . $row->id . '" >Hapus</a></li>
                       </ul>
                     </div>';
                    return $actionBtn;
                })->make(true);
        }

        // dd(module_path('Authentification'));
        return view('authentification::layouts.menus.index', compact('config'));
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        $config = [
            'title' => 'Tambah Module'
        ];

        $config['form'] = (object)[
            'method' => 'POST',
            'action' => route('module.store')
        ];
        $config['breadcrumbs'] = [
            ['label' => 'List Module', 'href' => route('module.index')],
            ['label' => 'Tambah Module']
        ];

        return view('authentification::layouts.menus.form', compact('config'));
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'permissions'        => 'required|array',
            'name'              => 'required|unique:menus',
            'href'              => 'required',
            'slug'              => 'required|unique:menus',
        ]);
        if ($validator->passes()) {
            DB::beginTransaction();
            try {
                $data = new Menu;
                $data->name = $request->name;
                $data->href = $request->href;
                $data->slug = $request->slug;
                $data->save();

                $data->permissions()->createMany($request->permissions);


                DB::commit();
                $response = response()->json($this->responseStore(true, NULL, route('module.index')));
            } catch (\Throwable $throw) {
                dd($throw);
                DB::rollBack();
                $response = response()->json($this->responseStore(false));
            }
        } else {
            $response = response()->json(['error' => $validator->errors()->all()]);
        }
        return $response;
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        return view('authentification::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        $config = [
            'title' => 'Edit Module'
        ];

        $config['form'] = (object)[
            'method' => 'PUT',
            'action' => route('module.update', $id)
        ];

        $data = Menu::with('permissions')->where('id', $id)->first();

        $config['breadcrumbs'] = [
            ['label' => 'List Module', 'href' => route('module.index')],
            ['label' => 'Edit Module']
        ];

        return view('authentification::layouts.menus.form', compact('config', 'data'));
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'permissions'               => 'required|array',
            'name'                      => 'required|unique:menus,name,' . $request['name'] . ',name',
            'href'                      => 'required',
            'slug'                      => 'required|unique:menus,slug,' . $request['slug'] . ',slug',
        ];

        foreach ($request->permissions as $key => $permission) {
            $rules = array_merge($rules, ['permissions.' . $key . '.name' => 'required|unique:permissions,name,' . $permission['name'] . ',name']);
        }

        $validator = Validator::make($request->all(), $rules);
        if ($validator->passes()) {
            DB::beginTransaction();
            try {
                $data = Menu::find($id);
                $data->name = $request->name;
                $data->href = $request->href;
                $data->slug = $request->slug;
                $data->save();

                $permissions = array_map(function ($item) use ($data) {
                    return [
                        'name'          => $item['name'],
                        'guard_name'    => $item['guard_name'],
                        'menu_id'       => $data->id
                    ];
                }, (isset($request['permissions']) ? $request['permissions'] : []));

                Permission::upsert(
                    $permissions,
                    ['name', 'guard_name', 'menu_id'],
                    ['name', 'guard_name', 'menu_id']
                );

                $usedPermission = [];

                foreach ($permissions as $key => $value) {
                    array_push($usedPermission, $value['name']);
                }


                $permission = Permission::where('menu_id', $data->id)->whereNotIn('name', $usedPermission)->delete();

                Artisan::call('cache:forget spatie.permission.cache ');

                DB::commit();
                $response = response()->json($this->responseStore(true, NULL, route('module.index')));
            } catch (\Throwable $throw) {
                dd($throw);
                DB::rollBack();
                $response = response()->json($this->responseStore(false));
            }
        } else {
            $response = response()->json(['error' => $validator->errors()->all()]);
        }
        return $response;
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy($id)
    {

        $response = response()->json([
            'status' => 'error',
            'message' => 'Data gagal dihapus'
        ]);
        DB::beginTransaction();

        try {
            $menu = Menu::find($id);
            $menu->permissions()->delete();
            $menu->delete();
            $response = response()->json([
                'status' => 'success',
                'message' => 'Data berhasil dihapus'
            ]);
            DB::commit();
        } catch (Throwable $throw) {
            dd($throw);
            $response = response()->json(['error' => $throw]);
        }

        return $response;
    }
}

Resources/views/layouts/menus/form.blade.php
@extends('authentification::layouts.main')
@section('contents')
<form id="formStore" action="{{ $config['form']->action }}" method="POST">
  @method($config['form']->method)
  @csrf
  <div class="col-md-12">
    <div id="errorCreate" class="mb-3" style="display:none;">
      <div class="alert alert-danger" role="alert">
        <div class="alert-icon"><i class="flaticon-danger text-danger"></i></div>
        <div class="alert-text">
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <div class="row">
            <div class="col-md-6 col-12 d-flex justify-content-center justify-content-md-start align-items-center mb-3 mb-md-0">
              <h3 class="card-title">Tambah Module</h3>
            </div>
            <div class="col-md-6 col-12 d-flex justify-content-center justify-content-md-end align-items-baseline mb-md-0 mb-2">
              <div class="btn-group float-md-right" role="group" aria-label="Button group with nested dropdown">
                <a onclick="history.back()" class="btn btn-outline-primary float-end">
                  <i class="fa-solid fa-rotate-left"></i> Kembali
                </a>
                <button type="submit" class="btn btn-success text-white float-end">
                  <i class="fa-solid fa-plus"></i> Simpan
                </button>
              </div>
            </div>
          </div>
        </div>
        <div class="mb-3 row">
          <label class="control-label col-sm-3 align-self-center mb-0" for="name">Nama :</label>
          <div class="col-sm-9">
            <input type="text" class="form-control" id="name" name="name" placeholder="Masukan Nama Module Anda" value="{{ $data->name ?? '' }}">
          </div>
        </div>
        <div class="mb-3 row">
          <label class="control-label col-sm-3 align-self-center mb-0" for="username">URI :</label>
          <div class="col-sm-9">
            <input type="text" class="form-control" id="href" name="href" placeholder="Masukan url module" value="{{ $data->href ?? '' }}">
          </div>
        </div>
        <div class="mb-3 row">
          <label class="control-label col-sm-3 align-self-center mb-0" for="email">slug :</label>
          <div class="col-sm-9">
            <input type="text" class="form-control" id="slug" name="slug" placeholder="Masukan slug" value="{{ $data->slug ?? '' }}">
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <div class="row">
            <div class="col-md-6 col-12 d-flex justify-content-center justify-content-md-start align-items-center mb-3 mb-md-0">
              <h3 class="card-title">Lits Module Permission</h3>
            </div>
            <div class="col-md-6 col-12 d-flex justify-content-center justify-content-md-end align-items-baseline mb-md-0 mb-2">
              <div class="btn-group float-md-right" role="group" aria-label="Button group with nested dropdown">
                <button type="button" class="btn btn-success text-white float-end" data-bs-toggle="modal" data-bs-target="#addPermissionModal">
                  <i class="fa-solid fa-plus"></i> Tambah Permission
                </button>
              </div>
            </div>
          </div>
        </div>
        <div class="table-responsive">
          <table id="dt" class="table table-bordered w-100">
            <thead>
              <tr>
                <th>Nama Permission</th>
                <th>Nama Guard</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody></tbody>
            </tr>
            </thead>
            <tbody></tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

</form>

<div id="addPermissionModal" class="modal fade">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Tambah Permission</h4>
        <button type="button" class="btn btn-outline-danger close" data-bs-dismiss="modal"><span>&times;</span></button>
      </div>
      <div class="modal-body">
        <div class="mb-3 row">
          <label class="control-label col-sm-3 align-self-center mb-0" for="name">Nama Permission:</label>
          <div class="col-sm-9">
            <input type="text" class="form-control" id="permissionName" name="name" placeholder="Masukan Nama Permission Anda" value="">
          </div>
        </div>
        <div class="mb-3 row">
          <label class="control-label col-sm-3 align-self-center mb-0" for="username">Nama Guard :</label>
          <div class="col-sm-9">
            <input type="text" class="form-control" id="guardName" name="guard_name" placeholder="Masukan Guard" value="">
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <div class="btn-group">
          <button type="button" class="btn btn-danger btn-sm" data-bs-dismiss="modal">Cancel <i class="fa fa-fw fa-ban"></i></button>
          <button type="button" id="add-permission" class="btn btn-success btn-sm">Tambah <i class="fa fa-fw fa-check"></i></button>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="editPermissionModal" class="modal fade">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Ubah Permission</h4>
        <button type="button" class="btn btn-outline-danger close" data-bs-dismiss="modal"><span>&times;</span></button>
      </div>
      <div class="modal-body">
        <input type="hidden" name="idPermission" />
        <div class="mb-3 row">
          <label class="control-label col-sm-3 align-self-center mb-0" for="name">Nama Permission:</label>
          <div class="col-sm-9">
            <input type="text" class="form-control" id="editPermissionName" name="name" placeholder="Masukan Nama Permission Anda" value="">
          </div>
        </div>
        <div class="mb-3 row">
          <label class="control-label col-sm-3 align-self-center mb-0" for="username">Nama Guard :</label>
          <div class="col-sm-9">
            <input type="text" class="form-control" id="editGuardName" name="guard_name" placeholder="Masukan Guard" value="">
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <div class="btn-group">
          <button type="button" class="btn btn-danger btn-sm" data-bs-dismiss="modal">Cancel <i class="fa fa-fw fa-ban"></i></button>
          <button type="button" id="edit-permission" class="btn btn-success btn-sm">Simpan <i class="fa fa-fw fa-check"></i></button>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection

@section('css')
<link rel="stylesheet" href="{{Module::asset('authentification:vendor/datatables/datatables.min.css')}}">
<link rel="stylesheet" href="{{Module::asset('authentification:vendor/select2/select2.min.css')}}">
<link rel="stylesheet" href="{{Module::asset('authentification:vendor/select2/select2-bootstrap-5-theme.min.css')}}">
@endsection

@section('scripts')
<script src="{{Module::asset('authentification:vendor/datatables/datatables.min.js')}}"></script>
<script src="{{Module::asset('authentification:vendor/select2/select2.full.min.js')}}"></script>
<script>
  $(document).ready(function() {
    let dt = $('#dt').DataTable({
      data: <?= isset($data->permissions) ? json_encode($data->permissions) : "[]"; ?>,
      info: false,
      paging: false,
      searching: false,
      ordering: false,
      columns: [{
          data: 'name',
          render: function(data, type, row, meta) {
            return `
                    <input type="hidden" name="permissions[${meta.row}][id]" value="${row.id}">
                    <input class="qty form-control form-control-sm text-right" name="permissions[${meta.row}][name]" value="${data}">`;
          }
        },
        {
          data: 'guard_name',
          render: function(data, type, row, meta) {
            return `<input class="qty form-control form-control-sm text-right" name="permissions[${meta.row}][guard_name]" value="${data}">`;
          }
        },
        {
          data: 'id',
          className: 'text-center',
          orderable: false,
          render: function(data, type, row, meta) {
            return `
                        <button type="button" class="btn btn-sm btn-secondary row-edit"><i class="fa-solid fa-pen-to-square"></i></button>
                        <button type="button" class="btn btn-sm btn-secondary row-remove"><i class="fa fa-minus"></i></button>
                        `;
          }
        }
      ],
      rowCallback: function(row, data, displayNum, displayIndex, dataIndex) {
        let api = this.api();

        $(row).find('.row-remove').click(function(e) {
          e.preventDefault();
          api.row(row).remove().draw();
        });

        $(row).find('.row-edit').click(function(e) {
          e.preventDefault();
          console.log(dataIndex);
          $('#editPermissionName').val(data.name);
          $('#editGuardName').val(data.guard_name);
          $('#idPermission').val(dataIndex);
          $('#editPermissionModal').modal('show');
        });
      },
    });

    $("#formStore").submit(function(e) {
      e.preventDefault();
      let form = $(this);
      let btnSubmit = form.find("[type='submit']");
      let btnSubmitHtml = btnSubmit.html();
      let url = form.attr("action");
      let data = new FormData(this);
      $.ajax({
        cache: false,
        processData: false,
        contentType: false,
        type: "POST",
        url: url,
        data: data,
        beforeSend: function() {
          btnSubmit.addClass("disabled").html('<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Loading...').prop("disabled", "disabled");
        },
        success: function(response) {
          let errorCreate = $('#errorCreate');
          errorCreate.css('display', 'none');
          errorCreate.find('.alert-text').html('');
          btnSubmit.removeClass("disabled").html(btnSubmitHtml).removeAttr("disabled");
          if (response.status === "success") {
            toastr.success(response.message, 'Success !');
            setTimeout(function() {
              if (response.redirect === "" || response.redirect === "reload") {
                location.reload();
              } else {
                location.href = response.redirect;
              }
            }, 1000);
          } else {
            toastr.error((response.message ? response.message : "Please complete your form"), 'Failed !');
            if (response.error !== undefined) {
              errorCreate.removeAttr('style');
              $.each(response.error, function(key, value) {
                errorCreate.find('.alert-text').append('<span style="display: block">' + value + '</span>');
              });
            }
          }
        },
        error: function(response) {
          btnSubmit.removeClass("disabled").html(btnSubmitHtml).removeAttr("disabled");
          toastr.error(response.responseJSON.message, 'Failed !');
        }
      });
    });

    $('#add-permission').click(function(e) {
      let permissionName = $('#permissionName').val(),
        guardName = $('#guardName').val();
      if (permissionName == '' || permissionName == undefined || permissionName == null || guardName == '' || guardName == undefined || guardName == null) {
        alert('Isi Form Terlebih Dahulu');
      } else {
        let data = {
          name: permissionName,
          guard_name: guardName,
        };
        dt.row.add(data).draw();
        $('#addPermissionModal').modal('hide');
        $('.modal-backdrop').remove();
      }
    });

    $('#addPermissionModal').on('hidden.bs.modal', function() {
      $('#permissionName').val(null);
      $('#guardName').val(null);
    });

    $('#editPermissionModal').on('hidden.bs.modal', function() {
      $('#editPermissionName').val(null);
      $('#editGuardName').val(null);
      $('#idPermission').val(null);
    });

    $('#edit-permission').click(function(e) {
      let permissionName = $('#editPermissionName').val(),
        guardName = $('#editGuardName').val(),
        idPermission = $('#idPermission').val();
      if (permissionName == '' || permissionName == undefined || permissionName == null || guardName == '' || guardName == undefined || guardName == null) {
        alert('Isi Form Terlebih Dahulu');
      } else {
        let data = {
          name: permissionName,
          guard_name: guardName,
        };
        dt.row(idPermission).data(data).draw();
        $('#editPermissionModal').modal('hide');
        $('.modal-backdrop').remove();
      }
    });
  });
</script>
@endsection

Resources/views/layouts/menus/index.blade.php
@extends('authentification::layouts.main')
@section('contents')
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <div class="row">
          <div class="col-md-6 col-12 d-flex justify-content-center justify-content-md-start align-items-center mb-3 mb-md-0">
            <h3 class="card-title">Daftar Modules</h3>
          </div>
          <div class="col-md-6 col-12 d-flex justify-content-center justify-content-md-end align-items-baseline mb-md-0 mb-2">
            <div class="btn-group float-md-right" role="group" aria-label="Button group with nested dropdown">
              <a class="btn btn-outline-primary" href=""><i class="fa fa-sync-alt fa-fw"></i></a>
              <a class="btn btn-outline-primary" href="{{ route('module.create') }}"><i class="fa fa-plus fa-fw"></i> Tambah</a>
            </div>
          </div>
        </div>
      </div>
      <div class="table-responsive">
        <table id="dt" class="table table-bordered w-100">
          <thead>
            <tr>
              <th>Nama</th>
              <th>Href</th>
              <th>Aksi</th>
            </tr>
          </thead>
          <tbody></tbody>
          </tr>
          </thead>
          <tbody></tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div id="confirmDeleteModal" class="modal fade">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Hapus Menu</h4>
        <button type="button" class="btn btn-outline-danger close" data-bs-dismiss="modal"><span>&times;</span></button>
      </div>
      <div class="modal-body">
        <input type="hidden" name="id" />
        <div class="alert alert-warning">
          <strong>Peringatan !</strong> Anda yakin menghapus data ini ?
        </div>
      </div>
      <div class="modal-footer">
        <div class="btn-group">
          <button type="button" class="btn btn-danger btn-sm" data-bs-dismiss="modal">No <i class="fa fa-fw fa-ban"></i></button>
          <button type="button" id="btnDelete" class="btn btn-success btn-sm">Yes <i class="fa fa-fw fa-check"></i></button>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection

@section('css')
<link rel="stylesheet" href="{{Module::asset('authentification:vendor/datatables/datatables.min.css')}}">
@endsection

@section('scripts')
<script src="{{Module::asset('authentification:vendor/datatables/datatables.min.js')}}"></script>
<script>
  $(document).ready(function() {
    $('#dt').DataTable({

      responsive: true,
      serverSide: true,
      processing: true,
      ajax: {
        url: `{{ route('module.index') }}`
      },
      columns: [{
          data: 'name',
          name: 'name'
        },
        {
          data: 'href',
          name: 'href'
        },
        {
          data: 'action',
          name: 'action',
          orderable: false,
          searchable: false
        },
      ],
      rowCallback: function(row, data) {
        let api = this.api();
        $(row).find('.btn-delete').click(function() {
          var pk = $(this).data('id'),
            url = `{{ route("module.index") }}/` + pk;

          $('#confirmDeleteModal').modal('toggle');

          $('#btnDelete').click(function(e) {
            e.preventDefault();
            $.ajax({
              url: url,
              type: "DELETE",
              data: {
                _token: '{{ csrf_token() }}',
                _method: 'DELETE'
              },
              error: function(response) {
                toastr.error(response, 'Failed !');
              },
              success: function(response) {
                if (response.status === "success") {
                  toastr.success(response.message, 'Success !');
                  $('#confirmDeleteModal').modal('hide');;
                  $('.modal-backdrop').remove();
                  api.draw();
                } else {
                  toastr.error((response.message ? response.message : "Please complete your form"), 'Failed !');
                }
              }
            });
          });
        });
      }
    });

  });
</script>
@endsection