Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Modules\Authentification\Http\Controllers\AuthentificationController;
use Modules\Authentification\Http\Controllers\DashboardController;
use Modules\Authentification\Http\Controllers\MenuController;
use Modules\Authentification\Http\Controllers\MenuManagerController;
use Modules\Authentification\Http\Controllers\RoleController;
use Modules\Authentification\Http\Controllers\SearchController;
use Modules\Authentification\Http\Controllers\UserController;


// Auth Route
Route::get('login', [AuthentificationController::class, 'showLogin'])->name('login');
Route::post('login', [AuthentificationController::class, 'login'])->name('login.post');
Route::post('logout', [AuthentificationController::class, 'logout'])->name('logout');


Route::middleware('auth')->group(function () {
    // Search Route
    Route::get('search/roles', [SearchController::class, 'roles'])->name('auth.searchRole');
    Route::get('search/module', [SearchController::class, 'modules'])->name('auth.searchModule');

    // Dashboard Route
    Route::resource('home', DashboardController::class);

    //  Users Route
    Route::resource('users', UserController::class);

    // Roles Route
    Route::resource('roles', RoleController::class);

    // Menu Route
    Route::resource('module', MenuController::class);

    // Menu Manager Route
    Route::post('menu-manager/changeHierarchy', [MenuManagerController::class, 'changeHierarchy'])->name('menu-manager.changeHierarchy');
    Route::resource('menu-manager', MenuManagerController::class);
});

Entities/User.php
<?php

namespace Modules\Authentification\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */

    protected $table = 'users';
    protected $guard_name = 'web';

    protected $primaryKey = 'id';
    protected $fillable = [
        'name',
        'username',
        'email',
        'image',
        'password',
        'active'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected static function newFactory()
    {
        return \Modules\Authentification\Database\factories\UserFactory::new();
    }
}

Http/Controllers/UserController.php
<?php

namespace Modules\Authentification\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use DataTables;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Modules\Authentification\Entities\User;
use Modules\Authentification\Traits\ResponseStatus;
use Modules\Authentification\Helpers\ImageUpload;

class UserController extends Controller
{
    use ResponseStatus;


    public function __construct()
    {
        $this->middleware('permission:users-index', ['only' => ['index']]);
        $this->middleware('permission:users-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:users-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:users-delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index(Request $request)
    {
        $config = [
            'title' => 'Pengguna'
        ];
        $config['breadcrumbs'] = [
            ['label' => 'List Pengguna']
        ];


        if ($request->ajax()) {
            $data = User::with('roles');
            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function ($row) {
                    $actionBtn = '<div class="btn-group dropend">
                       <button type="button" class="btn btn-outline-info dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                           Aksi
                       </button>
                       <ul class="dropdown-menu">
                           <li><a class="dropdown-item" href="' . route('users.edit', $row->id) . '">Edit</a></li>
                           <li><a class="dropdown-item btn-delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" data-id ="' . $row->id . '" >Hapus</a></li>
                       </ul>
                     </div>';
                    return $actionBtn;
                })->make(true);
        }

        // dd(module_path('Authentification'));
        return view('authentification::layouts.user.index', compact('config'));
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        $config = [
            'title' => 'Tambah Pengguna'
        ];

        $config['form'] = (object)[
            'method' => 'POST',
            'action' => route('users.store')
        ];
        $config['breadcrumbs'] = [
            ['label' => 'List Pengguna', 'href' => route('users.index')],
            ['label' => 'Tambah Pengguna']
        ];

        return view('authentification::layouts.user.form', compact('config'));
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'roles'         => 'required|array',
            'name'          => 'required',
            'username'      => 'required|alpha_dash|unique:users',
            'password'      => 'required|between:6,255|confirmed',
            'email'         => 'required|unique:users,email|email',
            'active'        => 'required|between:0,1',
            'image'         => 'nullable|image|mimes:jpeg,png,jpg,gif,svg|max:2024',
        ]);
        if ($validator->passes()) {
            DB::beginTransaction();
            try {
                $data = new User();
                $data->name = $request->name;
                $data->password = Hash::make($request->password);
                $data->username = $request->username;
                $data->email = $request->email;
                $data->active = $request->active;
                $data->image = ImageUpload::profilePicture('image', 'public');
                $data->save();

                $data->syncRoles($request['roles']);

                DB::commit();
                $response = response()->json($this->responseStore(true, NULL, route('users.index')));
            } catch (\Throwable $throw) {
                dd($throw);
                DB::rollBack();
                $response = response()->json($this->responseStore(false));
            }
        } else {
            $response = response()->json(['error' => $validator->errors()->all()]);
        }
        return $response;
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        return view('authentification::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        $config = [
            'title' => 'Edit Pengguna'
        ];

        $data = User::with('roles')->where('id', $id)->first();

        $config['form'] = (object)[
            'method' => 'PUT',
            'action' => route('users.update', $id)
        ];
        $config['breadcrumbs'] = [
            ['label' => 'List Pengguna', 'href' => route('users.index')],
            ['label' => 'Edit Pengguna']
        ];

        return view('authentification::layouts.user.form', compact('config', 'data'));
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'roles'         => 'required|array',
            'name'          => 'required',
            'email'         => 'required|email|unique:users,email,' . $request['email'] . ',email',
            'active'        => 'required|between:0,1',
            'image'         => 'nullable|image|mimes:jpeg,png,jpg,gif,svg|max:2024',
        ]);

        if ($validator->passes()) {
            DB::beginTransaction();
            try {
                $data = User::find($id);
                $data->update([
                    'name' => $request['name'],
                    'active' => $request['active'],
                ]);

                $data->roles()->sync($request['roles']);

                if (isset($request->image) && !empty($request->image)) {
                    $image = ImageUpload::profilePicture('image', 'public', $data->image);
                    $data->update(
                        [
                            'image' => $image
                        ]
                    );
                }
                DB::commit();
                $response = response()->json($this->responseStore(true, NULL, route('users.index')));
            } catch (Throwable $throw) {
                // dd($throw);
                DB::rollBack();
                $response = response()->json($this->responseStore(false));
            }
        } else {
            $response = response()->json(['error' => $validator->errors()->all()]);
        }
        return $response;
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy(User $user)
    {
        $response = response()->json([
            'status' => 'error',
            'message' => 'Data gagal dihapus'
        ]);
        DB::beginTransaction();

        try {
            $user->delete();
            $response = response()->json([
                'status' => 'success',
                'message' => 'Data berhasil dihapus'
            ]);
            DB::commit();
        } catch (Throwable $throw) {
            dd($throw);
            $response = response()->json(['error' => $throw]);
        }

        return $response;
    }
}

Resources/views/layouts/user/form.blade.php
@extends('authentification::layouts.main')
@section('contents')
<form id="formStore" action="{{ $config['form']->action }}" method="POST">
  @method($config['form']->method)
  @csrf
  <div class="col-md-12">
    <div id="errorCreate" class="mb-3" style="display:none;">
      <div class="alert alert-danger" role="alert">
        <div class="alert-icon"><i class="flaticon-danger text-danger"></i></div>
        <div class="alert-text">
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-7">
      <div class="card">
        <div class="card-header">
          <div class="row">
            <div class="col-md-6 col-12 d-flex justify-content-center justify-content-md-start align-items-center mb-3 mb-md-0">
              <h3 class="card-title">Tambah Pengguna</h3>
            </div>
            <div class="col-md-6 col-12 d-flex justify-content-center justify-content-md-end align-items-baseline mb-md-0 mb-2">
              <div class="btn-group float-md-right" role="group" aria-label="Button group with nested dropdown">
                <a onclick="history.back()" class="btn btn-outline-primary float-end">
                  <i class="fa-solid fa-rotate-left"></i> Kembali
                </a>
                <button type="submit" class="btn btn-success text-white float-end">
                  <i class="fa-solid fa-plus"></i> Simpan
                </button>
              </div>
            </div>
          </div>
        </div>
        <div class="mb-3 row">
          <label class="control-label col-sm-3 align-self-center mb-0" for="name">Nama :</label>
          <div class="col-sm-9">
            <input type="text" class="form-control" id="name" name="name" placeholder="Masukkan Nama Anda" value="{{ $data->name ?? '' }}">
          </div>
        </div>
        <div class="mb-3 row">
          <label class="control-label col-sm-3 align-self-center mb-0" for="username">Username :</label>
          <div class="col-sm-9">
            <input type="text" class="form-control" id="username" name="username" placeholder="Masukan Username Anda" value="{{ $data->username ?? '' }}" {{ (isset($data) ? 'readonly' : '') }}>
          </div>
        </div>
        <div class="mb-3 row">
          <label class="control-label col-sm-3 align-self-center mb-0" for="email">Email :</label>
          <div class="col-sm-9">
            <input type="text" class="form-control" id="email" name="email" placeholder="Masukan Email" value="{{ $data->email ?? '' }}" {{ (isset($data) ? 'readonly' : '') }}>
          </div>
        </div>
        <div class="mb-3 row">
          <label class="control-label col-sm-3 align-self-center mb-0" for="select2Role">Role :</label>
          <div class="col-sm-9">
            <select id="select2Role" style="width: 100% !important;" name="roles[]" multiple="multiple">
              @isset($data->roles)
              @foreach ($data->roles as $item)
              <option value="{{ $item->id }}" selected="selected">{{ $item->name }}</option>
              @endforeach
              @endisset
            </select>
          </div>
        </div>
        <div style="{{ isset($data) ? 'display:none' : '' }}">
          <div class="mb-3 row">
            <label class="control-label col-sm-3 align-self-center mb-0" for="password">Password :</label>
            <div class="col-sm-9">
              <input type="password" class="form-control" name="password" id="password" placeholder="Enter Your password">
            </div>
          </div>
          <div class="mb-3 row">
            <label class="control-label col-sm-3 align-self-center mb-0" for="confirm_password">Konfirmasi Password :</label>
            <div class="col-sm-9">
              <input type="password" class="form-control" id="confirm_password" name="password_confirmation" placeholder="Konfirmasi Password">
            </div>
          </div>
        </div>
        <div class="mb-3 row">
          <label class="control-label col-sm-3 align-self-center mb-0" for="active">Status :</label>
          <div class="col-sm-9">
            <select id="active" name="active" class="form-select" placeholder="Status User ?">
              <option value="1">Aktif</option>
              <option value="0">Tidak Aktif</option>
            </select>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-5">
      <div class="card">
        <div class="card-header">
          <div class="row">
            <div class="col-md-6 col-12 d-flex justify-content-center justify-content-md-start align-items-center mb-3 mb-md-0">
              <h3 class="card-title">Upload Foto Profile</h3>
            </div>
          </div>
        </div>
        <label class="mx-0 text-bold text-center d-block mb-3">Photo</label>
        <img id="avatar" src="{{ isset($data) && $data->image != NULL ? asset('images/user/thumbnail/'.$data->image) : Module::asset('authentification:img/profile/empty_profile.png') }}" style="object-fit: cover; border: 1px solid #d9d9d9" class="mb-2 border-2 mx-auto rounded-circle" height="150px" width="150px" alt="">
        <div class="row d-flex justify-content-center m-3">
          <input type="file" id="img-input" class="image d-block form-control form-control-sm" name="image" accept=".jpg, .jpeg, .png">
          <p class="text-center ms-75 mt-50"><small>Allowed JPG, JPEG or PNG. Max
              size of
              2000kB</small></p>
        </div>
      </div>
    </div>
  </div>
</form>


@endsection

@section('css')
<link rel="stylesheet" href="{{Module::asset('authentification:vendor/select2/select2.min.css')}}">
<link rel="stylesheet" href="{{Module::asset('authentification:vendor/select2/select2-bootstrap-5-theme.min.css')}}">
@endsection

@section('scripts')
<script src="{{Module::asset('authentification:vendor/select2/select2.full.min.js')}}"></script>
<script>
  $(document).ready(function() {

    $('#select2Role').select2({
      theme: "bootstrap-5",
      dropdownParent: $('#select2Role').parent(),
      placeholder: 'Pilih Roles',
      allowClear: true,
      multiple: true,
      ajax: {
        url: `{{ route('auth.searchRole') }}`,
        dataType: 'json',
        processResults: function(response) {
          let results = $.map(response.data, function(row, index) {
            row.id = row.id;
            row.text = row.name;
            return row;
          });
          return {
            results: results,
            pagination: {
              more: (response.next_page_url != null)
            }
          };
        }
      }
    });

    $("#img-input").change(function() {
      let thumb = $('#avatar');
      if (this.files && this.files[0]) {
        let reader = new FileReader();
        reader.onload = function(e) {
          thumb.attr('src', e.target.result);
        }
        reader.readAsDataURL(this.files[0]);
      }
    });

    $("#formStore").submit(function(e) {
      e.preventDefault();
      let form = $(this);
      let btnSubmit = form.find("[type='submit']");
      let btnSubmitHtml = btnSubmit.html();
      let url = form.attr("action");
      let data = new FormData(this);
      $.ajax({
        cache: false,
        processData: false,
        contentType: false,
        type: "POST",
        url: url,
        data: data,
        beforeSend: function() {
          btnSubmit.addClass("disabled").html('<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Loading...').prop("disabled", "disabled");
        },
        success: function(response) {
          let errorCreate = $('#errorCreate');
          errorCreate.css('display', 'none');
          errorCreate.find('.alert-text').html('');
          btnSubmit.removeClass("disabled").html(btnSubmitHtml).removeAttr("disabled");
          if (response.status === "success") {
            toastr.success(response.message, 'Success !');
            setTimeout(function() {
              if (response.redirect === "" || response.redirect === "reload") {
                location.reload();
              } else {
                location.href = response.redirect;
              }
            }, 1000);
          } else {
            toastr.error((response.message ? response.message : "Please complete your form"), 'Failed !');
            if (response.error !== undefined) {
              errorCreate.removeAttr('style');
              $.each(response.error, function(key, value) {
                errorCreate.find('.alert-text').append('<span style="display: block">' + value + '</span>');
              });
            }
          }
        },
        error: function(response) {
          btnSubmit.removeClass("disabled").html(btnSubmitHtml).removeAttr("disabled");
          toastr.error(response.responseJSON.message, 'Failed !');
        }
      });
    });

  });
</script>
@endsection

Resources/views/layouts/user/index.blade.php
@extends('authentification::layouts.main')
@section('contents')
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <div class="row">
          <div class="col-md-6 col-12 d-flex justify-content-center justify-content-md-start align-items-center mb-3 mb-md-0">
            <h3 class="card-title">Daftar Pengguna</h3>
          </div>
          <div class="col-md-6 col-12 d-flex justify-content-center justify-content-md-end align-items-baseline mb-md-0 mb-2">
            <div class="btn-group float-md-right" role="group" aria-label="Button group with nested dropdown">
              <a class="btn btn-outline-primary" href=""><i class="fa fa-sync-alt fa-fw"></i></a>
              <a class="btn btn-outline-primary" href="{{ route('users.create') }}"><i class="fa fa-plus fa-fw"></i> Tambah</a>
            </div>
          </div>
        </div>
      </div>
      <div class="table-responsive">
        <table id="dt" class="table table-bordered w-100">
          <thead>
            <tr>
              <th>Image</th>
              <th>Name</th>
              <th>Username</th>
              <th>Email</th>
              <th>Role</th>
              <th>Aktif</th>
              <th>Aksi</th>
            </tr>
          </thead>
          <tbody></tbody>
          </tr>
          </thead>
          <tbody></tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div id="confirmDeleteModal" class="modal fade">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Delete Item Confirm</h4>
        <button type="button" class="btn btn-outline-danger close" data-bs-dismiss="modal"><span>&times;</span></button>
      </div>
      <div class="modal-body">
        <input type="hidden" name="id" />
        <div class="alert alert-warning">
          <strong>Peringatan !</strong> Anda yakin menghapus data ini ?
        </div>
      </div>
      <div class="modal-footer">
        <div class="btn-group">
          <button type="button" class="btn btn-danger btn-sm" data-bs-dismiss="modal">No <i class="fa fa-fw fa-ban"></i></button>
          <button type="button" id="btnDelete" class="btn btn-success btn-sm">Yes <i class="fa fa-fw fa-check"></i></button>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection

@section('css')
<link rel="stylesheet" href="{{Module::asset('authentification:vendor/datatables/datatables.min.css')}}">
@endsection

@section('scripts')
<script src="{{Module::asset('authentification:vendor/datatables/datatables.min.js')}}"></script>
<script>
  $(document).ready(function() {
    $('#dt').DataTable({

      responsive: true,
      serverSide: true,
      processing: true,
      ajax: {
        url: `{{ route('users.index') }}`
      },

      columnDefs: [{
        className: 'text-center',
        width: '100px',
        orderable: false,
        targets: 0,
        render: function(data, type, full, meta) {
          if (data == null || data == undefined) {
            return ` <img class="rounded-circle" src=" {{ Module::asset('authentification:img/profile/empty_profile.png') }}" alt="photo" style="width: 50px; height: 50px;">`;
          } else {
            return ` <img class="rounded-circle" src=" {{ asset('images/user/thumbnail') }}/` + data + `" alt="photo" style="width: 50px; height: 50px;">`;
          }
        }
      }],
      columns: [{
          data: 'image',
          name: 'image'
        },
        {
          data: 'name',
          name: 'name'
        },
        {
          data: 'username',
          name: 'username'
        },
        {
          data: 'email',
          name: 'email'
        },
        {
          data: 'roles',
          name: 'roles.name',
          orderable: false,
          render: function(data, type, row, meta) {
            let html = ``;
            data.forEach(function(role, index) {
              html += `<span class="badge rounded-pill bg-primary">${role.name}</span>`;
            });
            console.log(html);
            return html;
          }
        },
        {
          data: 'active',
          name: 'active',
          render: function(data, type, row, meta) {
            if (data === 0) {
              return `<span class="badge bg-danger"> Tidak Aktif </span>`;
            } else {
              return `<span class="badge bg-success"> Aktif </span>`;
            }
          },
        },
        {
          data: 'action',
          name: 'action',
          orderable: false,
          searchable: false
        },
      ],
      rowCallback: function(row, data) {
        let api = this.api();
        $(row).find('.btn-delete').click(function() {
          var pk = $(this).data('id'),
            url = `{{ route("users.index") }}/` + pk;

          $('#confirmDeleteModal').modal('toggle');

          $('#btnDelete').click(function(e) {
            e.preventDefault();
            $.ajax({
              url: url,
              type: "DELETE",
              data: {
                _token: '{{ csrf_token() }}',
                _method: 'DELETE'
              },
              error: function(response) {
                toastr.error(response, 'Failed !');
              },
              success: function(response) {
                if (response.status === "success") {
                  toastr.success(response.message, 'Success !');
                  $('#confirmDeleteModal').modal('hide');;
                  $('.modal-backdrop').remove();
                  api.draw();
                } else {
                  toastr.error((response.message ? response.message : "Please complete your form"), 'Failed !');
                }
              }
            });
          });
        });
      }
    });

  });
</script>
@endsection